# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkSocialIconContainerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_social_icon_allinksocialiconcontainerplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AllinkSocialIconPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_social_icon_allinksocialiconplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='SEO text (not visible) e.g. Follow allink on Instagram', max_length=255, null=True, verbose_name='Title')),
                ('icon', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter'), ('snapchat', 'Snapchat'), ('linkedin', 'Linkedin'), ('spotify', 'Spotify'), ('xing', 'Xing'), ('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('googleplus', 'Google Plus'), ('tripadvisor', 'TripAdvisor'), ('kununu', 'kununu')], max_length=50, verbose_name='Icon')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
