# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkInfoBoxPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_info_box_allinkinfoboxplugin', serialize=False, to='cms.CMSPlugin')),
                ('counter', models.IntegerField(choices=[(0, 'Always visible'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text='After how many times/clicks should the box not be visible anymore', verbose_name='Display duration')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
