# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_info_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkinfoboxplugin',
            name='counter',
            field=models.IntegerField(choices=[(0, 'Always visible'), (1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x')], default=0, help_text='After how many times/clicks should the box not be visible anymore', verbose_name='Display duration'),
        ),
    ]
