# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_info_box', '0002_auto_20180216_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkinfoboxplugin',
            name='template',
            field=models.CharField(default='default', help_text='Choose a template.', max_length=50, verbose_name='Template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allinkinfoboxplugin',
            name='transparent_background',
            field=models.BooleanField(default=False, verbose_name='Transparent background'),
        ),
    ]
