# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-03 17:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkContentColumnPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_content_allinkcontentcolumnplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('order_mobile', models.IntegerField(blank=True, help_text='Some columns should be ordered differently on mobile devices when columns are stacked vertically. This option allows you to define the position of the this column.<br><br>Note: Columns ordering is ascending (lowest number displayed first)', null=True, verbose_name='Order Mobile')),
                ('alignment_horizontal_mobile', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text='This option overrides the projects default alignment for mobile. (Usually "left")', max_length=50, null=True, verbose_name='Alignment horizontal mobile')),
                ('alignment_horizontal_desktop', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], help_text='This option overrides the projects default alignment for desktop. (Usually "left")', max_length=50, null=True, verbose_name='Alignment horizontal desktop')),
                ('alignment_vertical_desktop', models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], help_text='This option overrides the projects default alignment for desktop. (Usually "top")', max_length=50, null=True, verbose_name='Alignment vertical desktop')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AllinkContentPlugin',
            fields=[
                ('title', models.CharField(blank=True, help_text='The section title', max_length=255, null=True, verbose_name='Title')),
                ('title_size', models.CharField(max_length=50, verbose_name='Section Title Size')),
                ('container_enabled', models.BooleanField(default=True, help_text='If checked, an inner container with a maximum width is added', verbose_name='Activate "container"')),
                ('bg_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Set a predefined background color')),
                ('template', models.CharField(help_text='Choose a template.', max_length=50, verbose_name='Template')),
                ('overlay_styles_enabled', models.BooleanField(default=False, help_text='If checked, the predefined overlay styles are applied (suitable when text is over an image/video)', verbose_name='Activate overlay styles')),
                ('full_height_enabled', models.BooleanField(default=False, help_text="If checked, the section will use the available height of the device's/browser's screen.", verbose_name='Activate "full height" mode')),
                ('dynamic_height_enabled', models.BooleanField(default=False, help_text='If checked, the section\'s height will grow depending on the height of its children.<br>Note: This option is being ignored when "full height" or "parallax" are enabled.', verbose_name='Activate dynamic height')),
                ('parallax_enabled', models.BooleanField(default=False, help_text='If checked, the parallax effect is enabled.', verbose_name='Activate Parallax effect')),
                ('anchor', models.CharField(blank=True, help_text='ID of this content section which can be used for anchor reference from links.<br>Note: Only letters, numbers and hyphen. No spaces or special chars.', max_length=255, verbose_name='ID')),
                ('ignore_in_pdf', models.BooleanField(default=False, help_text='If checked, the content plugin will be ignored when generting a pdf.', verbose_name='Ignore for pdf export')),
                ('project_css_classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('project_on_screen_effect', models.CharField(blank=True, default='default', max_length=50, null=True)),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_content_allinkcontentplugin', serialize=False, to='cms.CMSPlugin')),
                ('bg_image_inner_container', filer.fields.image.FilerImageField(blank=True, help_text='Adds a background image to the inner container of a content section. Activating "overlay styles" is recommended.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_container_bg_image', to='filer.Image', verbose_name='Background-Image')),
                ('bg_image_outer_container', filer.fields.image.FilerImageField(blank=True, help_text='Optional: Set a background image for the content section.<br>Note: This is meant for decorative purposes only and should be used with care.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allink_content_allinkcontentplugin_bg_image', to='filer.Image', verbose_name='Background-Image')),
                ('video_file', filer.fields.file.FilerFileField(blank=True, help_text='Recommended video settings:<br><br>Format: mp4<br>Codec: H.264<br>Target Bitrate: 2 (video loads quick and runs smooth)<br>Audio: Not recommended (no audio = smaller file size and less annoyed visitors)<br>File size: Dependent of video length. Generally speaking: Less is more.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_video_file', to='filer.File', verbose_name='Source')),
                ('video_mobile_image', filer.fields.image.FilerImageField(blank=True, help_text='The image that is being displayed instead of the video on mobile devices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_video_mobile_image', to='filer.Image', verbose_name='Mobile Image')),
                ('video_poster_image', filer.fields.image.FilerImageField(blank=True, help_text='This image is displayed while the video is loading. Ideally, use an exact screen capture image of the very first frame of the video.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_video_poster_image', to='filer.Image', verbose_name='Video Start Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
