repos:
-   repo: git://github.com/luismayta/pre-commit-isort
    rev: 1.0.1
    hooks:
    -   id: isort
        args:
        - -q
        - --recursive
        - --diff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: flake8
