# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-03 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_social_icon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinksocialiconcontainerplugin',
            name='project_css_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
