# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 14:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('allink_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkgalleryplugin',
            name='folder',
            field=filer.fields.folder.FilerFolderField(blank=True, help_text="All Images (.png, .gif, .jpg, .jpeg) will be used in gallery. If a folder is specified, the child plugin won't be rendered.", null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder'),
        ),
    ]
