# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_gallery', '0002_allinkgalleryplugin_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkgalleryplugin',
            name='fullscreen_enabled',
            field=models.BooleanField(default=True, help_text='This option enables a fullscreen button for this gallery.', verbose_name='Fullscreen option visible'),
        ),
    ]
