# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-11-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


def set_fields_on_children(apps, schema_editor):
    AllinkGalleryPlugin = apps.get_model("allink_gallery", "AllinkGalleryPlugin")
    AllinkGalleryImagePlugin = apps.get_model("allink_gallery", "AllinkGalleryImagePlugin")

    for child in AllinkGalleryImagePlugin.objects.all():
        try:
            parent = AllinkGalleryPlugin.objects.get(id=child.parent_id)

            child.template = parent.template
            child.ratio = parent.ratio

            child.save()
        except AllinkGalleryImagePlugin.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('allink_gallery', '0003_auto_20171127_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkgalleryimageplugin',
            name='ratio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='allinkgalleryimageplugin',
            name='template',
            field=models.CharField(help_text='Choose a template.', max_length=50, null=True, verbose_name='Template'),
        ),
        migrations.RunPython(set_fields_on_children),
    ]
