# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-05-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170720_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsappcontentplugin',
            name='manual_filtering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
