# Generated by Django 2.2.13 on 2020-11-03 13:55

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('news', '0007_newstranslation_teaser_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsappcontentplugin',
            name='load_more_link',
        ),
        migrations.AddField(
            model_name='newsappcontentplugin',
            name='load_more_internallink',
            field=cms.models.fields.PageField(blank=True, help_text='Link for Button Below Items if custom URL is chosen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_more_internallink_news', to='cms.Page', verbose_name='Custom Load More Link'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='teaser_link_url',
            field=models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=500, null=True, verbose_name='External link'),
        ),
    ]
