# Generated by Django 2.2.17 on 2025-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201103_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Wenn nofollow gesetzt ist, werden Suchmaschinen den Links auf der Seite nicht folgen.', verbose_name='nofollow'),
        ),
        migrations.AddField(
            model_name='news',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Wenn noindex gesetzt ist, wird die Seite nicht von Suchmaschinen indexiert.', verbose_name='noindex'),
        ),
    ]
