# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-28 14:55
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='We automatically handle phone number formatting, Please provide the number in the following format "+41 43 123 45 67".', max_length=128, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='We automatically handle phone number formatting, Please provide the number in the following format "+41 43 123 45 67".', max_length=128, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='We automatically handle phone number formatting, Please provide the number in the following format "+41 43 123 45 67".', max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
