# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-19 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20170720_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ('sort_order',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
