# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-05-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20171219_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsappcontentplugin',
            name='manual_filtering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
