# Generated by Django 2.2.13 on 2020-10-29 22:26

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('locations', '0006_auto_20201001_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsappcontentplugin',
            name='load_more_link',
        ),
        migrations.AddField(
            model_name='locationsappcontentplugin',
            name='load_more_internallink',
            field=cms.models.fields.PageField(blank=True, help_text='Link for Button Below Items if custom URL is chosen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_more_internallink_locations', to='cms.Page', verbose_name='Custom Load More Link'),
        ),
    ]
