# Generated by Django 2.2.17 on 2021-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201130_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstranslation',
            name='country_translatable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
    ]
