# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0002_allinklegacylink_redirect_when_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinklegacylink',
            name='redirect_when_logged_in',
        ),
        migrations.AddField(
            model_name='allinklegacylink',
            name='redirect_when_logged_out',
            field=models.BooleanField(default=False, help_text='If True, current site will not redirect when user is logged in. If False, the page will be redirected.', verbose_name='Redirect when logged out'),
        ),
    ]
