# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0003_auto_20170711_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(max_length=200, null=True, verbose_name='Language'),
        ),
    ]
