# Generated by Django 2.2.16 on 2021-03-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkTeaserGridContainerPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_teaser_grid_allinkteasergridcontainerplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('project_css_spacings_top_bottom', models.CharField(blank=True, help_text='Choose a spacing (top and bottom).', max_length=50, null=True, verbose_name='Spacings')),
                ('project_css_spacings_top', models.CharField(blank=True, help_text='Choose a top spacing.', max_length=50, null=True, verbose_name='Spacings top')),
                ('project_css_spacings_bottom', models.CharField(blank=True, help_text='Choose a bottom spacing.', max_length=50, null=True, verbose_name='Spacings bottom')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
