# Generated by Django 2.2.16 on 2021-03-18 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_teaser_grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkteasergridcontainerplugin',
            name='anchor',
            field=models.CharField(blank=True, help_text='ID of this content section which can be used for anchor reference from links.<br>Note: Only letters, numbers and hyphen. No spaces or special chars.', max_length=255, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='allinkteasergridcontainerplugin',
            name='column_order',
            field=models.CharField(choices=[('default', 'Default'), ('inverted', 'Inverted'), ('alternating', 'Alternating')], default=('default', 'Default'), help_text='Choose a column order.', max_length=50, verbose_name='Column Order'),
        ),
        migrations.AddField(
            model_name='allinkteasergridcontainerplugin',
            name='project_css_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='allinkteasergridcontainerplugin',
            name='template',
            field=models.CharField(choices=[('1-of-1', 'One Column'), ('1-of-2', 'Two Columns'), ('1-of-3', 'Three Columns'), ('1-of-4', 'Four Columns')], default=('1-of-1', 'One Column'), help_text='Choose a template.', max_length=50, verbose_name='Template'),
        ),
    ]
