# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 09:32
from __future__ import unicode_literals

import cms.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkLegacyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_object_id', models.IntegerField(help_text='To which object directs the url.', null=True)),
                ('link_model', models.CharField(help_text='Dotted Path to referenced Model', max_length=300, null=True)),
                ('link_url_name', models.CharField(help_text='Name of the App-URL to use.', max_length=64, null=True)),
                ('link_url_kwargs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, help_text='Keyword arguments used to reverse url.', null=True, size=None)),
                ('old', models.CharField(max_length=255, unique=True, verbose_name='Old Link')),
                ('overwrite', models.CharField(blank=True, help_text="Overwrites 'New Page', use for special urls that are not listed there", max_length=255, null=True, verbose_name='Overwrite Link')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('match_subpages', models.BooleanField(default=False, help_text='If True, matches all subpages and redirects them to this link.', verbose_name='Match subpages')),
                ('last_test_result', models.NullBooleanField(default=None, help_text='Was the last automatic test successfull? (True = Yes, False = No, None = Not yet tested)', verbose_name='Result of last test')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of last test')),
                ('link_apphook_page', cms.models.fields.PageField(help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allink_legacy_redirect_allinklegacylink_app_legacy_redirects', to='cms.Page', verbose_name='New Apphook-Page')),
                ('link_page', cms.models.fields.PageField(help_text='If provided, overrides the external link and New Apphook-Page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='New Page')),
            ],
            options={
                'verbose_name': 'Legacy Link',
                'verbose_name_plural': 'Legacy Links',
            },
        ),
    ]
