# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinklegacylink',
            name='redirect_when_logged_in',
            field=models.BooleanField(default=False, help_text='If True, current site will be redirected to translated language. If False, it redirects to the homepage', verbose_name='Redirect when logged in'),
        ),
    ]
