# Generated by Django 3.2.18 on 2023-04-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('allink_legacy_redirect', '0003_alter_allinklegacylink_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinklegacylink',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
            preserve_default=False,
        ),
    ]
