# Generated by Django 3.2.18 on 2023-04-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('allink_legacy_redirect', '0004_allinklegacylink_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
        ),
    ]
