# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0005_auto_20170713_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default=('en', 'English'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
