# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0008_auto_20171107_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('zh-hans', 'Simplified Chinese')], default=('en', 'English'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
