# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-05-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0009_auto_20171114_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('nl', 'Dutch'), ('ru', 'Russian'), ('zh-hans', 'Simplified Chinese'), ('it', 'Italian')], default=('de', 'German'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
