# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-06-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0010_auto_20180504_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('nl', 'Dutch'), ('ru', 'Russian'), ('zh-hans', 'Simplified Chinese'), ('it', 'Italian')], default=('en', 'English'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
