# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-07-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0011_auto_20180622_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='old',
            field=models.CharField(help_text='We strip away the anchor part of the URL as this part is not passed to the server.', max_length=255, unique=True, verbose_name='Old Link'),
        ),
    ]
