# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-10-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0012_auto_20180730_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('de', 'German')], default=('de', 'German'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
