# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-12-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_legacy_redirect', '0013_auto_20181009_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinklegacylink',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('fr', 'French')], default=('de', 'German'), max_length=200, null=True, verbose_name='Language'),
        ),
    ]
