# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_content', '0002_auto_20170707_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkcontentplugin',
            name='overlay_enabled',
            field=models.BooleanField(default=False, help_text='If checked, a predefined overlay background gradient/color is applied.<br><strong>Important:</strong> Only applied when used in combination with a background image/video/color', verbose_name='Activate "overlay"'),
        ),
    ]
