# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('allink_content', '0003_auto_20170707_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkcontentplugin',
            name='ignore_in_pdf',
            field=models.BooleanField(default=False, help_text='If checked, this content section will be ignored when generting a pdf.', verbose_name='Ignore for pdf export'),
        ),
        migrations.AlterField(
            model_name='allinkcontentplugin',
            name='video_mobile_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='The image that is being displayed on mobile devices instead of the video.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_video_mobile_image', to='filer.Image', verbose_name='Mobile Image'),
        ),
    ]
