# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2019-02-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_content', '0005_auto_20170810_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkcontentplugin',
            name='project_css_spacings_bottom',
            field=models.CharField(blank=True, help_text='Choose a bottom spacing.', max_length=50, null=True, verbose_name='Spacings bottom'),
        ),
        migrations.AddField(
            model_name='allinkcontentplugin',
            name='project_css_spacings_top',
            field=models.CharField(blank=True, help_text='Choose a top spacing.', max_length=50, null=True, verbose_name='Spacings top'),
        ),
        migrations.AddField(
            model_name='allinkcontentplugin',
            name='project_css_spacings_top_bottom',
            field=models.CharField(blank=True, help_text='Choose a spacing (top and bottom).', max_length=50, null=True, verbose_name='Spacings'),
        ),
    ]
