# Generated by Django 2.1.10 on 2019-10-02 20:20

import aldryn_common.admin_fields.sortedm2m
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_peopleappcontentplugin_filter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleappcontentplugin',
            name='manual_entries',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text='Select and arrange specific entries, or, leave blank to select all. (If manual entries are selected the category filtering will be applied as well.)', to='people.People'),
        ),
    ]
