# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 10:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0005_auto_20170712_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='label_layout',
            field=models.CharField(choices=[('stacked', 'Stacked with fields'), ('side_by_side', 'Side by side with fields'), ('placeholder', 'As placeholders')], default='stacked', max_length=15, verbose_name='Display labels'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='project_css_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='send_external_mail',
            field=models.BooleanField(default=True, help_text='Send confirmation mail to customer.', verbose_name='Send external e-mail'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='thank_you_text',
            field=models.TextField(blank=True, help_text='This text will be shown, after form completion.', null=True, verbose_name='Thank you text'),
        ),
    ]
