# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0006_auto_20170713_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='send_internal_mail',
            field=models.BooleanField(default=True, help_text='Send confirmation mail to defined internal e-mail addresses.', verbose_name='Send internal e-mail'),
        ),
    ]
