# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-28 16:50
from __future__ import unicode_literals

import adminsortable.fields
import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('just_descendants', models.BooleanField(default=False, help_text='If checked and pages selected manually, only the descendants of the selected pages will be listed.', verbose_name='Select just descendants')),
                ('page', cms.models.fields.PageField(on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'verbose_name_plural': 'Pages',
                'verbose_name': 'Page',
            },
        ),
        migrations.CreateModel(
            name='AllinkPageChooserPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_cms_allinkpagechooserplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='allinkpage',
            name='pagechooser',
            field=adminsortable.fields.SortableForeignKey(blank=True, help_text='Add pages and order them.', null=True, on_delete=django.db.models.deletion.CASCADE, to='allink_cms.AllinkPageChooserPlugin', verbose_name='Images'),
        ),
    ]
