# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkimageplugin',
            name='link_target',
            field=models.IntegerField(blank=True, choices=[(1, 'New window'), (2, 'Softpage (large)'), (3, 'Softpage (small)'), (4, 'Lightbox (Forms)'), (5, 'Lightbox (Image)')], help_text='Recommended combinations:<br><br>- Link Internal: No selection (loads page in current window/tab) or any of the <strong>Softpage</strong> options<br>- Link External: <strong>New window</strong><br>- Special Links (usually forms): <strong>Lightbox (Forms)</strong><br>- Link to an image: <strong>Lightbox (Image)</strong><br>- Link to a document (e.g. PDF): <strong>New window</strong><br>', null=True, verbose_name='Link Target'),
        ),
    ]
