# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_image', '0002_auto_20170704_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkimageplugin',
            name='link_anchor',
            field=models.CharField(blank=True, help_text='Appends the value only after the internal or external link.<br>Do <strong>not</strong> include a preceding "#" symbol.', max_length=255, verbose_name='Anchor'),
        ),
    ]
