# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_image', '0005_auto_20170823_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkimageplugin',
            name='width_alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Width Alias'),
        ),
    ]
