# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_image', '0006_allinkimageplugin_width_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkimageplugin',
            name='link_target',
            field=models.IntegerField(blank=True, choices=[(1, 'New window'), (2, 'Softpage (large)'), (3, 'Softpage (small)'), (4, 'Lightbox (Forms)'), (5, 'Lightbox (Image)'), (6, 'Lightbox (Default)')], null=True, verbose_name='Link Target'),
        ),
    ]
