# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-12 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0004_auto_20170712_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='from_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sender e-mail address'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='internal_email_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None, verbose_name='Internal e-mail addresses'),
        ),
    ]
