# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0007_allinkbuttonlinkplugin_send_internal_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='send_external_mail',
            field=models.BooleanField(default=False, help_text='Send confirmation mail to customer.', verbose_name='Send external e-mail'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='send_internal_mail',
            field=models.BooleanField(default=False, help_text='Send confirmation mail to defined internal e-mail addresses.', verbose_name='Send internal e-mail'),
        ),
    ]
