# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('allink_button_link', '0009_auto_20170823_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='allow_fullscreen_enabled',
            field=models.BooleanField(default=True, verbose_name='Allow fullscreen'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='auto_start_enabled',
            field=models.BooleanField(default=False, help_text='<strong>Important:</strong> Autoplaying videos with audio is not recommended. Use wisely. ', verbose_name='Autostart'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='poster_only_on_mobile',
            field=models.BooleanField(default=True, help_text='Disable video on mobile devices and only show the start image without video control.', verbose_name='Image Only (Mobile)'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='ratio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='template',
            field=models.CharField(choices=[('default_link', 'Internal/External'), ('file_link', 'File (Download)'), ('image_link', 'Image'), ('phone_link', 'Phone'), ('email_link', 'Email'), ('form_link', 'Form'), ('video_embedded_link', 'Video (Embedded)')], default='default_link', help_text='Choose a link type in order to display its options below.', max_length=50, verbose_name='Link type'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_file',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Recommended video settings:<br><br>Format: mp4<br>Codec: H.264<br>Target Bitrate: 2 (video loads quick and runs smooth)<br>Audio: Not recommended (no audio = smaller file size and less annoyed visitors)<br>File size: Dependent of video length. Generally speaking: Less is more.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allink_button_link_allinkbuttonlinkplugin_video_file', to='filer.File', verbose_name='Video File'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_file_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Video height'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_file_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Video width'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_id',
            field=models.CharField(blank=True, help_text='Only provide the ID. The correct URL will automatically be generated.<br><br>YouTube: https://www.youtube.com/watch?v=<strong>12345678</strong> (the ID is <strong>12345678</strong>)<br>Vimeo: https://vimeo.com/<strong>12345678</strong> (the ID is <strong>12345678</strong>)', max_length=255, null=True, verbose_name='Video ID'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_muted_enabled',
            field=models.BooleanField(default=True, help_text='Caution: Autoplaying videos with audio is not recommended. Use wisely.', verbose_name='Muted'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_poster_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Image that is being displayed while the video is loading. Ideally the very first frame of the video is used, in order to make the transition as smooth as possible.<br><br><strong>Imoprtant:</strong> Make sure the aspect ratio of the image is <strong>exactly the same</strong> as the video, otherwise the video height will shrink or grow when the playback starts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allink_button_link_allinkbuttonlinkplugin_video_poster_image', to='filer.Image', verbose_name='Video Start Image'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='video_service',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=50, null=True, verbose_name='Video Service'),
        ),
    ]
