# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-14 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0011_auto_20180214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='template',
            field=models.CharField(choices=[('default_link', 'Internal/External'), ('file_link', 'File (Download)'), ('image_link', 'Image'), ('phone_link', 'Phone'), ('email_link', 'Email'), ('form_link', 'Form'), ('video_embedded_link', 'Video (Embedded)'), ('video_file_link', 'Video (File)')], default='default_link', help_text='Choose a link type in order to display its options below.', max_length=50, verbose_name='Link type'),
        ),
    ]
