# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0012_auto_20180214_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_button_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Button close enabled'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_escape_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Escape close enabled'),
        ),
        migrations.AddField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_overlay_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Overlay close enabled'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='link_target',
            field=models.IntegerField(blank=True, choices=[(1, 'New window'), (2, 'Softpage (large)'), (3, 'Softpage (small)'), (4, 'Lightbox (Forms)'), (5, 'Lightbox (Image)'), (6, 'Lightbox (Default)')], null=True, verbose_name='Link Target'),
        ),
    ]
