# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-26 13:54
from __future__ import unicode_literals

import allink_core.core_apps.allink_button_link.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0013_auto_20180215_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='btn_context',
            field=allink_core.core_apps.allink_button_link.model_fields.Context(choices=[('default', 'Default'), ('primary', 'Primary'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('link', 'Link')], default='default', max_length=255, verbose_name='Variation'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_button_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Display close button'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_escape_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Escape key closes modal'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='data_modal_overlay_close_enabled',
            field=models.BooleanField(default=True, verbose_name='Click on overlay closes modal'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='allinkbuttonlinkplugin',
            name='type',
            field=allink_core.core_apps.allink_button_link.model_fields.LinkOrButton(default='lnk', max_length=255, verbose_name='Display type'),
        ),
    ]
