# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0014_auto_20180226_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinkbuttonlinkplugin',
            name='poster_only_on_mobile',
        ),
    ]
