# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allink_button_link', '0015_remove_allinkbuttonlinkplugin_poster_only_on_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinkbuttonlinkplugin',
            name='video_file_height',
        ),
        migrations.RemoveField(
            model_name='allinkbuttonlinkplugin',
            name='video_file_width',
        ),
    ]
