# Generated by Django 2.1.10 on 2019-07-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='quote_quoteplugin', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(verbose_name='Quote Text')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Name')),
                ('author_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
