# Generated by Django 2.2.5 on 2019-10-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allink_quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_quote_quoteplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
