# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20170704_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='is_active',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], default=1, verbose_name='status'),
        ),
    ]
