# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-05-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20170719_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialsappcontentplugin',
            name='manual_filtering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
