# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-17 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20170710_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksearchplugin',
            name='project_css_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='worksearchplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='work_worksearchplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
