# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20170720_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksearchplugin',
            name='template',
            field=models.CharField(default='search_grid_static', help_text='Choose a template.', max_length=50, verbose_name='Template'),
        ),
    ]
