# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-08-31 10:13
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('work', '0005_worksearchplugin_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workappcontentplugin',
            name='apphook_page',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, this Apphook-Page will be used to generate the detail link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Apphook Page'),
        ),
        migrations.AddField(
            model_name='workappcontentplugin',
            name='manual_filtering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
