# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2020-09-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_seo_accordion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkseoaccordioncontainerplugin',
            name='is_seo_faq',
            field=models.BooleanField(default=False, help_text='Enable to display accordion contents as questions/answers in search engine result pages', verbose_name='Enable SEO FAQ schema'),
        ),
    ]
