# Generated by Django 2.2.13 on 2020-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_seo_accordion', '0002_allinkseoaccordioncontainerplugin_is_seo_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkseoaccordioncontainerplugin',
            name='is_seo_faq',
            field=models.BooleanField(default=True, help_text='Enable to display accordion contents as questions/answers in search engine result pages', verbose_name='Enable SEO FAQ schema'),
        ),
    ]
