# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(blank=True, help_text='Theme color for Android Chrome', max_length=50, null=True, verbose_name='Theme Color')),
                ('mask_icon_color', models.CharField(blank=True, help_text='Mask icon color for safari-pinned-tab.svg', max_length=50, null=True, verbose_name='Mask icon color')),
                ('msapplication_tilecolor', models.CharField(blank=True, help_text='MS application TitleColor Field', max_length=50, null=True, verbose_name='msapplication TileColor')),
                ('gallery_plugin_caption_text_max_length', models.IntegerField(blank=True, null=True, verbose_name='Gallery Plugin max length of caption text Field')),
                ('news_verbose', models.CharField(default='News entry', max_length=255, verbose_name='News verbose name')),
                ('news_verbose_plural', models.CharField(default='News', max_length=255, verbose_name='News verbose name plural')),
                ('news_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('events_verbose', models.CharField(default='Event', max_length=255, verbose_name='Events verbose name')),
                ('events_verbose_plural', models.CharField(default='Events', max_length=255, verbose_name='Events verbose name plural')),
                ('events_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('eventsregistration_verbose', models.CharField(default='Event Registration', max_length=255, verbose_name='Events Registration verbose name')),
                ('eventsregistration_verbose_plural', models.CharField(default='Event Registrations', max_length=255, verbose_name='Events Registration verbose name plural')),
                ('eventsregistration_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('locations_verbose', models.CharField(default='Location', max_length=255, verbose_name='Locations verbose name')),
                ('locations_verbose_plural', models.CharField(default='Locations', max_length=255, verbose_name='Locations verbose name plural')),
                ('locations_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('people_verbose', models.CharField(default='Person', max_length=255, verbose_name='People verbose name')),
                ('people_verbose_plural', models.CharField(default='People', max_length=255, verbose_name='People verbose name plural')),
                ('people_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('testimonials_verbose', models.CharField(default='Testimonial', max_length=255, verbose_name='Testimonials verbose name')),
                ('testimonials_verbose_plural', models.CharField(default='Testimonials', max_length=255, verbose_name='Testimonials verbose name plural')),
                ('testimonials_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('work_verbose', models.CharField(default='Project/ Reference', max_length=255, verbose_name='Work verbose name')),
                ('work_verbose_plural', models.CharField(default='Projects/ References', max_length=255, verbose_name='Work verbose name plural')),
                ('work_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('members_verbose', models.CharField(default='Member', max_length=255, verbose_name='Members verbose name')),
                ('members_verbose_plural', models.CharField(default='Members', max_length=255, verbose_name='Members verbose name plural')),
                ('members_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('contactrequest_verbose', models.CharField(default='Contact request', max_length=255, verbose_name='Contact verbose name')),
                ('contactrequest_verbose_plural', models.CharField(default='Contact requests', max_length=255, verbose_name='Contact verbose name plural')),
                ('contactrequest_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('terms_verbose', models.CharField(default='Terms of Service', max_length=255, verbose_name='Terms of Service verbose name')),
                ('terms_verbose_plural', models.CharField(default='Terms of Service', max_length=255, verbose_name='Terms of Service verbose name plural')),
                ('terms_toolbar_enabled', models.BooleanField(default=True, verbose_name='Toolbar enabled?')),
                ('google_site_verification', models.CharField(blank=True, max_length=64, null=True, verbose_name='Google Site Verification Code')),
                ('default_to_email', models.EmailField(default='itcrowd@allink.ch', max_length=255, verbose_name='Default to email')),
                ('default_from_email', models.EmailField(default='itcrowd@allink.ch', max_length=255, verbose_name='Default from email')),
                ('default_og_image', filer.fields.image.FilerImageField(blank=True, help_text='Default preview image when page/post is shared on Facebook. <br>Min. 1200 x 630 for best results.', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='og:image')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Configuration',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('default_base_title', models.CharField(blank=True, help_text='Default base title, Is also used for default base og:title when page/post is shared on Facebook. <br>If not supplied the name form Django Sites will be used instead.', max_length=50, null=True, verbose_name='Base title')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='config.Config')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
