# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_allinkpageextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='config_allink_page_toolbar_enabled',
            field=models.BooleanField(default=False, verbose_name='allink Page Extension Toolbar Enabled?'),
        ),
    ]
