# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_config_allink_page_toolbar_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='contactrequest_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='contactrequest_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='contactrequest_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='events_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='events_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='events_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='eventsregistration_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='eventsregistration_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='eventsregistration_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='locations_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='locations_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='locations_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='members_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='members_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='members_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='news_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='news_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='news_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='people_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='people_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='people_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='terms_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='terms_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='terms_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='testimonials_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='testimonials_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='testimonials_verbose_plural',
        ),
        migrations.RemoveField(
            model_name='config',
            name='work_toolbar_enabled',
        ),
        migrations.RemoveField(
            model_name='config',
            name='work_verbose',
        ),
        migrations.RemoveField(
            model_name='config',
            name='work_verbose_plural',
        ),
    ]
