# Generated by Django 2.2.16 on 2020-10-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200124_1010'),
    ]

    operations = [
        migrations.RunSQL("""DELETE FROM django_migrations WHERE app='contact' AND name='0001_initial';""")
    ]
