# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('config', '0004_auto_20171107_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkTitleExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Title')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='config.AllinkTitleExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
