# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-06-20 09:50
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_allinktitleextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtranslation',
            name='newsletter_declaration_of_consent',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Detailed declaration of consent.', null=True, verbose_name='Declaration of consent'),
        ),
        migrations.AddField(
            model_name='configtranslation',
            name='newsletter_lead',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Teaser text in the newsletter signup view (data usage explainer).', null=True, verbose_name='Newsletter Signup Text'),
        ),
    ]
