# Generated by Django 2.2.16 on 2020-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_contact_migration_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinktitleextension',
            name='teaser_link_url',
            field=models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=500, null=True, verbose_name='External link'),
        ),
    ]
