# Generated by Django 2.2.17 on 2025-09-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('config', '0006_auto_20201103_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkpageextension',
            name='nofollow',
            field=models.BooleanField(default=False, help_text='Wenn nofollow gesetzt ist, werden Suchmaschinen den Links auf der Seite nicht folgen.', verbose_name='nofollow'),
        ),
        migrations.AddField(
            model_name='allinkpageextension',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Wenn noindex gesetzt ist, wird die Seite nicht von Suchmaschinen indexiert.', verbose_name='noindex'),
        ),
        migrations.CreateModel(
            name='AllinkNoindexExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noindex', models.BooleanField(default=False, help_text='Wenn noindex gesetzt ist, wird die Seite nicht von Suchmaschinen indexiert.', verbose_name='noindex')),
                ('nofollow', models.BooleanField(default=False, help_text='Wenn nofollow gesetzt ist, werden Suchmaschinen den Links auf der Seite nicht folgen.', verbose_name='nofollow')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('og_image', filer.fields.image.FilerImageField(blank=True, help_text='og: image is used when shared on Facebook/ Twitter etc. (Min. 1200 x 630 px)<br>Page: 1. fallback is teaser_image, 2. fallback is field allink_config.default_og_image.<br>App: 1. fallback = preview_image 2. fallback is teaser_image, 3. fallback is defined in allink_config.default_og_image.<br>', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_allinknoindexextension_og_image', to=settings.FILER_IMAGE_MODEL, verbose_name='og:Image')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='config.AllinkNoindexExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
