# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-08-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20180620_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='config_allink_page_toolbar_enabled',
        ),
    ]
