# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='language',
            field=models.CharField(default='en', max_length=3, verbose_name='Language'),
        ),
    ]
