# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinkSEOExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_base_title', models.BooleanField(default=False, help_text='If disabled, only the page title will be shown. Everything behind and including the "|" will be removed.', verbose_name='Disable base title')),
                ('override_h1', models.CharField(blank=True, help_text='Page Title or App title is default. This option allows you to override the h1 tag.', max_length=255, null=True, verbose_name='Override H1')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Title')),
                ('og_image', filer.fields.image.FilerImageField(blank=True, help_text='Preview image when page/post is shared on Facebook/ Twitter. <br>Min. 1200 x 630 for best results. If not set, the one from the preview image will be used, if not set or not in a app context, the one defined in allink_settings will be used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='og:Image')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='allink_seo.AllinkSEOExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
