# -*- coding: utf-8 -*-
# Generated by Django 1.9.13post1 on 2018-05-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170719_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsappcontentplugin',
            name='manual_filtering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
