# Generated by Django 2.2.7 on 2020-05-12 13:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('salutation', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.')], verbose_name='Salutation')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('allows_gdpr_email', models.BooleanField(verbose_name='consent for email dispatch')),
                ('allows_gdpr_direct_mailing', models.BooleanField(blank=True, verbose_name='consent for direct mailings')),
                ('allows_gdpr_personalised_marketing', models.BooleanField(blank=True, verbose_name='consent for personalised marketing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignupPlugin',
            fields=[
                ('form_text', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='This text will be shown, before the actual form fields and later replaced with the success message.', verbose_name='Form text')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='External email subject')),
                ('from_email_address', models.EmailField(default=None, max_length=254, verbose_name='From e-mail address')),
                ('internal_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, null=True, size=None, verbose_name='Internal e-mail recipients')),
                ('success_message', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='This text will be shown, after form completion.', verbose_name='Success message')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='allink_newsletter_newslettersignupplugin', serialize=False, to='cms.CMSPlugin')),
                ('audience_id', models.CharField(help_text='This is the id of the Mailchimp Audience the user wil be subscribed to', max_length=255, verbose_name='audience id')),
                ('consent_text', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='consent text')),
                ('double_opt_in_enabled', models.BooleanField(blank=True, default=False, help_text='If selected an email wil be sent where the user will have to confirm his subscribtion to the mailing list', verbose_name='Double-Opt-In')),
                ('marketing_permission_email_id', models.CharField(blank=True, help_text='Get this id via Postman and only change it if you know what you are doing', max_length=64, verbose_name='Mailchimp Email ID')),
                ('marketing_permission_personalised_marketing_id', models.CharField(blank=True, help_text='Get this id via Postman and only change it if you know what you are doing', max_length=64, verbose_name='Mailchimp Personalised Marketing ID')),
                ('marketing_permission_direct_mailing_id', models.CharField(blank=True, help_text='Get this id via Postman and only change it if you know what you are doing', max_length=64, verbose_name='Mailchimp Direct Mailing ID')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
