# Generated by Django 2.2.12 on 2020-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_teaser', '0006_auto_20200205_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinkteaserplugin',
            name='link_target',
            field=models.IntegerField(blank=True, choices=[(1, 'New window'), (2, 'Softpage')], null=True, verbose_name='Link Target'),
        ),
    ]
