# Generated by Django 2.2.16 on 2021-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allink_teaser', '0009_allinkteasergridcontainerplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinkteasergridcontainerplugin',
            name='column_order',
            field=models.CharField(help_text='Choose a column order.', max_length=50, verbose_name='Column Order'),
        ),
        migrations.AlterField(
            model_name='allinkteasergridcontainerplugin',
            name='columns',
            field=models.CharField(help_text='Choose columns.', max_length=50, verbose_name='Columns'),
        ),
    ]
